//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWebClient.CarRentalService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayRentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterNumber {
            get {
                return this.RegisterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterNumberField, value) != true)) {
                    this.RegisterNumberField = value;
                    this.RaisePropertyChanged("RegisterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int DayRent {
            get {
                return this.DayRentField;
            }
            set {
                if ((this.DayRentField.Equals(value) != true)) {
                    this.DayRentField = value;
                    this.RaisePropertyChanged("DayRent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerType", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    public enum CustomerType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayAsGoCustomer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContractCustomer = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CarRentalWebClient.CarRentalService.PayAsGoCustomer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CarRentalWebClient.CarRentalService.ContractCustomer))]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalWebClient.CarRentalService.CustomerType CustomerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalWebClient.CarRentalService.CustomerType CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((this.CustomerTypeField.Equals(value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayAsGoCustomer", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    [System.SerializableAttribute()]
    public partial class PayAsGoCustomer : CarRentalWebClient.CarRentalService.Customer {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractCustomer", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    [System.SerializableAttribute()]
    public partial class ContractCustomer : CarRentalWebClient.CarRentalService.Customer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/CarRentalService")]
    [System.SerializableAttribute()]
    public partial class Booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalWebClient.CarRentalService.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalWebClient.CarRentalService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReturnTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalWebClient.CarRentalService.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarId {
            get {
                return this.CarIdField;
            }
            set {
                if ((this.CarIdField.Equals(value) != true)) {
                    this.CarIdField = value;
                    this.RaisePropertyChanged("CarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalWebClient.CarRentalService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReturnTime {
            get {
                return this.ReturnTimeField;
            }
            set {
                if ((this.ReturnTimeField.Equals(value) != true)) {
                    this.ReturnTimeField = value;
                    this.RaisePropertyChanged("ReturnTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalService.ICarRentalService")]
    public interface ICarRentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/GetCar", ReplyAction="http://tempuri.org/ICarRentalService/GetCarResponse")]
        CarRentalWebClient.CarRentalService.CarInfo GetCar(CarRentalWebClient.CarRentalService.CarRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/GetCar", ReplyAction="http://tempuri.org/ICarRentalService/GetCarResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CarInfo> GetCarAsync(CarRentalWebClient.CarRentalService.CarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/GetCars", ReplyAction="http://tempuri.org/ICarRentalService/GetCarsResponse")]
        CarRentalWebClient.CarRentalService.Car[] GetCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/GetCars", ReplyAction="http://tempuri.org/ICarRentalService/GetCarsResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car[]> GetCarsAsync();
        
        // CODEGEN: Generating message contract since the operation SaveCar is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/SaveCar", ReplyAction="http://tempuri.org/ICarRentalService/SaveCarResponse")]
        CarRentalWebClient.CarRentalService.SaveCarResponse SaveCar(CarRentalWebClient.CarRentalService.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/SaveCar", ReplyAction="http://tempuri.org/ICarRentalService/SaveCarResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCarResponse> SaveCarAsync(CarRentalWebClient.CarRentalService.CarInfo request);
        
        // CODEGEN: Generating message contract since the operation UpdateCarStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/UpdateCarStatus", ReplyAction="http://tempuri.org/ICarRentalService/UpdateCarStatusResponse")]
        CarRentalWebClient.CarRentalService.UpdateCarStatusResponse UpdateCarStatus(CarRentalWebClient.CarRentalService.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/UpdateCarStatus", ReplyAction="http://tempuri.org/ICarRentalService/UpdateCarStatusResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCarStatusResponse> UpdateCarStatusAsync(CarRentalWebClient.CarRentalService.CarInfo request);
        
        // CODEGEN: Generating message contract since the operation DeleteCar is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/DeleteCar", ReplyAction="http://tempuri.org/ICarRentalService/DeleteCarResponse")]
        CarRentalWebClient.CarRentalService.DeleteCarResponse DeleteCar(CarRentalWebClient.CarRentalService.CarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalService/DeleteCar", ReplyAction="http://tempuri.org/ICarRentalService/DeleteCarResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCarResponse> DeleteCarAsync(CarRentalWebClient.CarRentalService.CarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarRequestObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CarId;
        
        public CarRequest() {
        }
        
        public CarRequest(string LicenseKey, int CarId) {
            this.LicenseKey = LicenseKey;
            this.CarId = CarId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarInfoObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string RegisterNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int DayRent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int Year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Status;
        
        public CarInfo() {
        }
        
        public CarInfo(int Id, string RegisterNumber, string Brand, string Model, int DayRent, int Year, string Status) {
            this.Id = Id;
            this.RegisterNumber = RegisterNumber;
            this.Brand = Brand;
            this.Model = Model;
            this.DayRent = DayRent;
            this.Year = Year;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCarResponse {
        
        public SaveCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarStatusResponse {
        
        public UpdateCarStatusResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCarResponse {
        
        public DeleteCarResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarRentalServiceChannel : CarRentalWebClient.CarRentalService.ICarRentalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarRentalServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.ICarRentalService>, CarRentalWebClient.CarRentalService.ICarRentalService {
        
        public CarRentalServiceClient() {
        }
        
        public CarRentalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarRentalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.CarInfo CarRentalWebClient.CarRentalService.ICarRentalService.GetCar(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.GetCar(request);
        }
        
        public int GetCar(string LicenseKey, int CarId, out string RegisterNumber, out string Brand, out string Model, out int DayRent, out int Year, out string Status) {
            CarRentalWebClient.CarRentalService.CarRequest inValue = new CarRentalWebClient.CarRentalService.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CarId = CarId;
            CarRentalWebClient.CarRentalService.CarInfo retVal = ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).GetCar(inValue);
            RegisterNumber = retVal.RegisterNumber;
            Brand = retVal.Brand;
            Model = retVal.Model;
            DayRent = retVal.DayRent;
            Year = retVal.Year;
            Status = retVal.Status;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CarInfo> GetCarAsync(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.GetCarAsync(request);
        }
        
        public CarRentalWebClient.CarRentalService.Car[] GetCars() {
            return base.Channel.GetCars();
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Car[]> GetCarsAsync() {
            return base.Channel.GetCarsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.SaveCarResponse CarRentalWebClient.CarRentalService.ICarRentalService.SaveCar(CarRentalWebClient.CarRentalService.CarInfo request) {
            return base.Channel.SaveCar(request);
        }
        
        public void SaveCar(int Id, string RegisterNumber, string Brand, string Model, int DayRent, int Year, string Status) {
            CarRentalWebClient.CarRentalService.CarInfo inValue = new CarRentalWebClient.CarRentalService.CarInfo();
            inValue.Id = Id;
            inValue.RegisterNumber = RegisterNumber;
            inValue.Brand = Brand;
            inValue.Model = Model;
            inValue.DayRent = DayRent;
            inValue.Year = Year;
            inValue.Status = Status;
            CarRentalWebClient.CarRentalService.SaveCarResponse retVal = ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).SaveCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCarResponse> CarRentalWebClient.CarRentalService.ICarRentalService.SaveCarAsync(CarRentalWebClient.CarRentalService.CarInfo request) {
            return base.Channel.SaveCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCarResponse> SaveCarAsync(int Id, string RegisterNumber, string Brand, string Model, int DayRent, int Year, string Status) {
            CarRentalWebClient.CarRentalService.CarInfo inValue = new CarRentalWebClient.CarRentalService.CarInfo();
            inValue.Id = Id;
            inValue.RegisterNumber = RegisterNumber;
            inValue.Brand = Brand;
            inValue.Model = Model;
            inValue.DayRent = DayRent;
            inValue.Year = Year;
            inValue.Status = Status;
            return ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).SaveCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.UpdateCarStatusResponse CarRentalWebClient.CarRentalService.ICarRentalService.UpdateCarStatus(CarRentalWebClient.CarRentalService.CarInfo request) {
            return base.Channel.UpdateCarStatus(request);
        }
        
        public void UpdateCarStatus(int Id, string RegisterNumber, string Brand, string Model, int DayRent, int Year, string Status) {
            CarRentalWebClient.CarRentalService.CarInfo inValue = new CarRentalWebClient.CarRentalService.CarInfo();
            inValue.Id = Id;
            inValue.RegisterNumber = RegisterNumber;
            inValue.Brand = Brand;
            inValue.Model = Model;
            inValue.DayRent = DayRent;
            inValue.Year = Year;
            inValue.Status = Status;
            CarRentalWebClient.CarRentalService.UpdateCarStatusResponse retVal = ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).UpdateCarStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCarStatusResponse> CarRentalWebClient.CarRentalService.ICarRentalService.UpdateCarStatusAsync(CarRentalWebClient.CarRentalService.CarInfo request) {
            return base.Channel.UpdateCarStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCarStatusResponse> UpdateCarStatusAsync(int Id, string RegisterNumber, string Brand, string Model, int DayRent, int Year, string Status) {
            CarRentalWebClient.CarRentalService.CarInfo inValue = new CarRentalWebClient.CarRentalService.CarInfo();
            inValue.Id = Id;
            inValue.RegisterNumber = RegisterNumber;
            inValue.Brand = Brand;
            inValue.Model = Model;
            inValue.DayRent = DayRent;
            inValue.Year = Year;
            inValue.Status = Status;
            return ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).UpdateCarStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.DeleteCarResponse CarRentalWebClient.CarRentalService.ICarRentalService.DeleteCar(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.DeleteCar(request);
        }
        
        public void DeleteCar(string LicenseKey, int CarId) {
            CarRentalWebClient.CarRentalService.CarRequest inValue = new CarRentalWebClient.CarRentalService.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CarId = CarId;
            CarRentalWebClient.CarRentalService.DeleteCarResponse retVal = ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).DeleteCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCarResponse> CarRentalWebClient.CarRentalService.ICarRentalService.DeleteCarAsync(CarRentalWebClient.CarRentalService.CarRequest request) {
            return base.Channel.DeleteCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCarResponse> DeleteCarAsync(string LicenseKey, int CarId) {
            CarRentalWebClient.CarRentalService.CarRequest inValue = new CarRentalWebClient.CarRentalService.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CarId = CarId;
            return ((CarRentalWebClient.CarRentalService.ICarRentalService)(this)).DeleteCarAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerResponse")]
        CarRentalWebClient.CarRentalService.CustomerInfo GetCustomer(CarRentalWebClient.CarRentalService.CustomerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomer", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CustomerInfo> GetCustomerAsync(CarRentalWebClient.CarRentalService.CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        CarRentalWebClient.CarRentalService.Customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Customer[]> GetCustomersAsync();
        
        // CODEGEN: Generating message contract since the operation SaveCustomer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SaveCustomer", ReplyAction="http://tempuri.org/ICustomerService/SaveCustomerResponse")]
        CarRentalWebClient.CarRentalService.SaveCustomerResponse SaveCustomer(CarRentalWebClient.CarRentalService.CustomerInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/SaveCustomer", ReplyAction="http://tempuri.org/ICustomerService/SaveCustomerResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCustomerResponse> SaveCustomerAsync(CarRentalWebClient.CarRentalService.CustomerInfo request);
        
        // CODEGEN: Generating message contract since the operation UpdateCustomer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
        CarRentalWebClient.CarRentalService.UpdateCustomerResponse UpdateCustomer(CarRentalWebClient.CarRentalService.CustomerInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCustomerResponse> UpdateCustomerAsync(CarRentalWebClient.CarRentalService.CustomerInfo request);
        
        // CODEGEN: Generating message contract since the operation DeleteCustomer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        CarRentalWebClient.CarRentalService.DeleteCustomerResponse DeleteCustomer(CarRentalWebClient.CarRentalService.CustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCustomerResponse> DeleteCustomerAsync(CarRentalWebClient.CarRentalService.CustomerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerRequestObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CustomerId;
        
        public CustomerRequest() {
        }
        
        public CustomerRequest(string LicenseKey, int CustomerId) {
            this.LicenseKey = LicenseKey;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerInfoObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomerInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public CarRentalWebClient.CarRentalService.CustomerType CustomerType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public decimal Discount;
        
        public CustomerInfo() {
        }
        
        public CustomerInfo(int Id, string FirstName, string LastName, string Mobile, string Email, CarRentalWebClient.CarRentalService.CustomerType CustomerType, decimal Discount) {
            this.Id = Id;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Mobile = Mobile;
            this.Email = Email;
            this.CustomerType = CustomerType;
            this.Discount = Discount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveCustomerResponse {
        
        public SaveCustomerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        public UpdateCustomerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCustomerResponse {
        
        public DeleteCustomerResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : CarRentalWebClient.CarRentalService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.ICustomerService>, CarRentalWebClient.CarRentalService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.CustomerInfo CarRentalWebClient.CarRentalService.ICustomerService.GetCustomer(CarRentalWebClient.CarRentalService.CustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public int GetCustomer(string LicenseKey, int CustomerId, out string FirstName, out string LastName, out string Mobile, out string Email, out CarRentalWebClient.CarRentalService.CustomerType CustomerType, out decimal Discount) {
            CarRentalWebClient.CarRentalService.CustomerRequest inValue = new CarRentalWebClient.CarRentalService.CustomerRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CustomerId = CustomerId;
            CarRentalWebClient.CarRentalService.CustomerInfo retVal = ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).GetCustomer(inValue);
            FirstName = retVal.FirstName;
            LastName = retVal.LastName;
            Mobile = retVal.Mobile;
            Email = retVal.Email;
            CustomerType = retVal.CustomerType;
            Discount = retVal.Discount;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.CustomerInfo> GetCustomerAsync(CarRentalWebClient.CarRentalService.CustomerRequest request) {
            return base.Channel.GetCustomerAsync(request);
        }
        
        public CarRentalWebClient.CarRentalService.Customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.SaveCustomerResponse CarRentalWebClient.CarRentalService.ICustomerService.SaveCustomer(CarRentalWebClient.CarRentalService.CustomerInfo request) {
            return base.Channel.SaveCustomer(request);
        }
        
        public void SaveCustomer(int Id, string FirstName, string LastName, string Mobile, string Email, CarRentalWebClient.CarRentalService.CustomerType CustomerType, decimal Discount) {
            CarRentalWebClient.CarRentalService.CustomerInfo inValue = new CarRentalWebClient.CarRentalService.CustomerInfo();
            inValue.Id = Id;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Mobile = Mobile;
            inValue.Email = Email;
            inValue.CustomerType = CustomerType;
            inValue.Discount = Discount;
            CarRentalWebClient.CarRentalService.SaveCustomerResponse retVal = ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).SaveCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCustomerResponse> CarRentalWebClient.CarRentalService.ICustomerService.SaveCustomerAsync(CarRentalWebClient.CarRentalService.CustomerInfo request) {
            return base.Channel.SaveCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveCustomerResponse> SaveCustomerAsync(int Id, string FirstName, string LastName, string Mobile, string Email, CarRentalWebClient.CarRentalService.CustomerType CustomerType, decimal Discount) {
            CarRentalWebClient.CarRentalService.CustomerInfo inValue = new CarRentalWebClient.CarRentalService.CustomerInfo();
            inValue.Id = Id;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Mobile = Mobile;
            inValue.Email = Email;
            inValue.CustomerType = CustomerType;
            inValue.Discount = Discount;
            return ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).SaveCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.UpdateCustomerResponse CarRentalWebClient.CarRentalService.ICustomerService.UpdateCustomer(CarRentalWebClient.CarRentalService.CustomerInfo request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public void UpdateCustomer(int Id, string FirstName, string LastName, string Mobile, string Email, CarRentalWebClient.CarRentalService.CustomerType CustomerType, decimal Discount) {
            CarRentalWebClient.CarRentalService.CustomerInfo inValue = new CarRentalWebClient.CarRentalService.CustomerInfo();
            inValue.Id = Id;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Mobile = Mobile;
            inValue.Email = Email;
            inValue.CustomerType = CustomerType;
            inValue.Discount = Discount;
            CarRentalWebClient.CarRentalService.UpdateCustomerResponse retVal = ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).UpdateCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCustomerResponse> CarRentalWebClient.CarRentalService.ICustomerService.UpdateCustomerAsync(CarRentalWebClient.CarRentalService.CustomerInfo request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.UpdateCustomerResponse> UpdateCustomerAsync(int Id, string FirstName, string LastName, string Mobile, string Email, CarRentalWebClient.CarRentalService.CustomerType CustomerType, decimal Discount) {
            CarRentalWebClient.CarRentalService.CustomerInfo inValue = new CarRentalWebClient.CarRentalService.CustomerInfo();
            inValue.Id = Id;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Mobile = Mobile;
            inValue.Email = Email;
            inValue.CustomerType = CustomerType;
            inValue.Discount = Discount;
            return ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).UpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.DeleteCustomerResponse CarRentalWebClient.CarRentalService.ICustomerService.DeleteCustomer(CarRentalWebClient.CarRentalService.CustomerRequest request) {
            return base.Channel.DeleteCustomer(request);
        }
        
        public void DeleteCustomer(string LicenseKey, int CustomerId) {
            CarRentalWebClient.CarRentalService.CustomerRequest inValue = new CarRentalWebClient.CarRentalService.CustomerRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CustomerId = CustomerId;
            CarRentalWebClient.CarRentalService.DeleteCustomerResponse retVal = ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).DeleteCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCustomerResponse> CarRentalWebClient.CarRentalService.ICustomerService.DeleteCustomerAsync(CarRentalWebClient.CarRentalService.CustomerRequest request) {
            return base.Channel.DeleteCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteCustomerResponse> DeleteCustomerAsync(string LicenseKey, int CustomerId) {
            CarRentalWebClient.CarRentalService.CustomerRequest inValue = new CarRentalWebClient.CarRentalService.CustomerRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.CustomerId = CustomerId;
            return ((CarRentalWebClient.CarRentalService.ICustomerService)(this)).DeleteCustomerAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalService.IBookingService")]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBooking", ReplyAction="http://tempuri.org/IBookingService/GetBookingResponse")]
        CarRentalWebClient.CarRentalService.BookingInfo GetBooking(CarRentalWebClient.CarRentalService.BookingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBooking", ReplyAction="http://tempuri.org/IBookingService/GetBookingResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.BookingInfo> GetBookingAsync(CarRentalWebClient.CarRentalService.BookingRequest request);
        
        // CODEGEN: Generating message contract since the operation SaveBooking is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/SaveBooking", ReplyAction="http://tempuri.org/IBookingService/SaveBookingResponse")]
        CarRentalWebClient.CarRentalService.SaveBookingResponse SaveBooking(CarRentalWebClient.CarRentalService.BookingInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/SaveBooking", ReplyAction="http://tempuri.org/IBookingService/SaveBookingResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveBookingResponse> SaveBookingAsync(CarRentalWebClient.CarRentalService.BookingInfo request);
        
        // CODEGEN: Generating message contract since the operation DeleteBooking is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/DeleteBooking", ReplyAction="http://tempuri.org/IBookingService/DeleteBookingResponse")]
        CarRentalWebClient.CarRentalService.DeleteBookingResponse DeleteBooking(CarRentalWebClient.CarRentalService.BookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/DeleteBooking", ReplyAction="http://tempuri.org/IBookingService/DeleteBookingResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteBookingResponse> DeleteBookingAsync(CarRentalWebClient.CarRentalService.BookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBookings", ReplyAction="http://tempuri.org/IBookingService/GetBookingsResponse")]
        CarRentalWebClient.CarRentalService.Booking[] GetBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBookings", ReplyAction="http://tempuri.org/IBookingService/GetBookingsResponse")]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking[]> GetBookingsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingRequestObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int BookingId;
        
        public BookingRequest() {
        }
        
        public BookingRequest(string LicenseKey, int BookingId) {
            this.LicenseKey = LicenseKey;
            this.BookingId = BookingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BookingInfoObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BookingInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime ReturnTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int CustomerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int CarId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public CarRentalWebClient.CarRentalService.Customer Customer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public CarRentalWebClient.CarRentalService.Car Car;
        
        public BookingInfo() {
        }
        
        public BookingInfo(int Id, System.DateTime StartTime, System.DateTime ReturnTime, int CustomerId, int CarId, CarRentalWebClient.CarRentalService.Customer Customer, CarRentalWebClient.CarRentalService.Car Car) {
            this.Id = Id;
            this.StartTime = StartTime;
            this.ReturnTime = ReturnTime;
            this.CustomerId = CustomerId;
            this.CarId = CarId;
            this.Customer = Customer;
            this.Car = Car;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBookingResponse {
        
        public SaveBookingResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookingResponse {
        
        public DeleteBookingResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : CarRentalWebClient.CarRentalService.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<CarRentalWebClient.CarRentalService.IBookingService>, CarRentalWebClient.CarRentalService.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.BookingInfo CarRentalWebClient.CarRentalService.IBookingService.GetBooking(CarRentalWebClient.CarRentalService.BookingRequest request) {
            return base.Channel.GetBooking(request);
        }
        
        public int GetBooking(string LicenseKey, int BookingId, out System.DateTime StartTime, out System.DateTime ReturnTime, out int CustomerId, out int CarId, out CarRentalWebClient.CarRentalService.Customer Customer, out CarRentalWebClient.CarRentalService.Car Car) {
            CarRentalWebClient.CarRentalService.BookingRequest inValue = new CarRentalWebClient.CarRentalService.BookingRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.BookingId = BookingId;
            CarRentalWebClient.CarRentalService.BookingInfo retVal = ((CarRentalWebClient.CarRentalService.IBookingService)(this)).GetBooking(inValue);
            StartTime = retVal.StartTime;
            ReturnTime = retVal.ReturnTime;
            CustomerId = retVal.CustomerId;
            CarId = retVal.CarId;
            Customer = retVal.Customer;
            Car = retVal.Car;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.BookingInfo> GetBookingAsync(CarRentalWebClient.CarRentalService.BookingRequest request) {
            return base.Channel.GetBookingAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.SaveBookingResponse CarRentalWebClient.CarRentalService.IBookingService.SaveBooking(CarRentalWebClient.CarRentalService.BookingInfo request) {
            return base.Channel.SaveBooking(request);
        }
        
        public void SaveBooking(int Id, System.DateTime StartTime, System.DateTime ReturnTime, int CustomerId, int CarId, CarRentalWebClient.CarRentalService.Customer Customer, CarRentalWebClient.CarRentalService.Car Car) {
            CarRentalWebClient.CarRentalService.BookingInfo inValue = new CarRentalWebClient.CarRentalService.BookingInfo();
            inValue.Id = Id;
            inValue.StartTime = StartTime;
            inValue.ReturnTime = ReturnTime;
            inValue.CustomerId = CustomerId;
            inValue.CarId = CarId;
            inValue.Customer = Customer;
            inValue.Car = Car;
            CarRentalWebClient.CarRentalService.SaveBookingResponse retVal = ((CarRentalWebClient.CarRentalService.IBookingService)(this)).SaveBooking(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveBookingResponse> CarRentalWebClient.CarRentalService.IBookingService.SaveBookingAsync(CarRentalWebClient.CarRentalService.BookingInfo request) {
            return base.Channel.SaveBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.SaveBookingResponse> SaveBookingAsync(int Id, System.DateTime StartTime, System.DateTime ReturnTime, int CustomerId, int CarId, CarRentalWebClient.CarRentalService.Customer Customer, CarRentalWebClient.CarRentalService.Car Car) {
            CarRentalWebClient.CarRentalService.BookingInfo inValue = new CarRentalWebClient.CarRentalService.BookingInfo();
            inValue.Id = Id;
            inValue.StartTime = StartTime;
            inValue.ReturnTime = ReturnTime;
            inValue.CustomerId = CustomerId;
            inValue.CarId = CarId;
            inValue.Customer = Customer;
            inValue.Car = Car;
            return ((CarRentalWebClient.CarRentalService.IBookingService)(this)).SaveBookingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarRentalWebClient.CarRentalService.DeleteBookingResponse CarRentalWebClient.CarRentalService.IBookingService.DeleteBooking(CarRentalWebClient.CarRentalService.BookingRequest request) {
            return base.Channel.DeleteBooking(request);
        }
        
        public void DeleteBooking(string LicenseKey, int BookingId) {
            CarRentalWebClient.CarRentalService.BookingRequest inValue = new CarRentalWebClient.CarRentalService.BookingRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.BookingId = BookingId;
            CarRentalWebClient.CarRentalService.DeleteBookingResponse retVal = ((CarRentalWebClient.CarRentalService.IBookingService)(this)).DeleteBooking(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteBookingResponse> CarRentalWebClient.CarRentalService.IBookingService.DeleteBookingAsync(CarRentalWebClient.CarRentalService.BookingRequest request) {
            return base.Channel.DeleteBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.DeleteBookingResponse> DeleteBookingAsync(string LicenseKey, int BookingId) {
            CarRentalWebClient.CarRentalService.BookingRequest inValue = new CarRentalWebClient.CarRentalService.BookingRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.BookingId = BookingId;
            return ((CarRentalWebClient.CarRentalService.IBookingService)(this)).DeleteBookingAsync(inValue);
        }
        
        public CarRentalWebClient.CarRentalService.Booking[] GetBookings() {
            return base.Channel.GetBookings();
        }
        
        public System.Threading.Tasks.Task<CarRentalWebClient.CarRentalService.Booking[]> GetBookingsAsync() {
            return base.Channel.GetBookingsAsync();
        }
    }
}
